version: "3.2"

services:
  resident-vulnerabilities-data-pipeline:
    image: resident-vulnerabilities-data-pipeline
    build:
      context: ResidentVulnerabilitiesDataPipeline/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
      - database.env
    environment:
      - DB_HOST=test-database
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12

  resident-vulnerabilities-data-pipeline-test:
    image: resident-vulnerabilities-data-pipeline-test
    build:
      context: .
      dockerfile: ResidentVulnerabilitiesDataPipeline.Tests/Dockerfile
    env_file:
      - database.env
    environment:
      - DB_HOST=test-database
    links:
      - test-database
  test-database:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=resident-vulnerabilities-data-pipeline-test-db
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
